### ISSUE TITLE
Task: Make CLI compatible with `/api/v1/root` endpoint

### ISSUE THREAD

**Issue by kairoaraujo** [vmware/repository-service-tuf-cli#221]
### What is the task about?

The RSTUF API no longer supports the `/api/v1/bootstrap` endpoint. The CLI must update its calls to `/api/v1/root`.

(When the below task is complete)
- [x] https://github.com/vmware/repository-service-tuf-api/issues/288

We need to update the CLI to change the endpoint calls.

### Parent feature

- https://github.com/vmware/repository-service-tuf/issues/23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MVrachev** [comment]
After a discussion with @kairoaraujo we realized that by renaming `/api/v1/bootstrap` to `/api/v1/root` we limit ourselfs on how we can use this API endpoint.
In the future, it's possible that additional information could be added to the payload expected by this API and even today we don't share information exclusively only about root but for `targets` settings as well.
That's we decided this issue is obsolete.
